# -*- mode: ruby -*-
# vi: ft=ruby

# Adds a `openwrt_relase` custom fact, fetched from projects root
$add_facter = <<SCRIPT
  sudo mkdir -p /etc/facter/facts.d
  sudo cp /vagrant/provisioning/scripts/openwrt_release.sh /etc/facter/facts.d
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define :builder do |builder|
    builder.vm.box = "ubuntu-base"

    builder.vm.hostname = "openwrt.builder.wilbur.org"

    builder.vm.provider :virtualbox do |vbox|
      vbox.customize ["modifyvm", :id, "--memory", "1024"]
    end

    builder.ssh.username = "ops"

    builder.vm.provision :shell, :inline => $add_facter

    builder.vm.provision :puppet do |puppet|
      puppet.manifests_path = "provisioning/manifests"
      puppet.manifest_file  = "builder.pp"
    end
  end

  config.vm.define :provisioner do |provisioner|
    provisioner.vm.box = "centos-base"

    provisioner.vm.hostname = "openwrt.provisioning.wilbur.org"

    provisioner.vm.provider :virtualbox do |vbox|
      vbox.customize ["modifyvm", :id, "--memory", "512"]
    end

    provisioner.ssh.username = "ops"

    provisioner.vm.provision :puppet do |puppet|
      puppet.manifests_path = "provisioning/manifests"
      puppet.manifest_file  = "provisioner.pp"
    end
  end
end
